/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from https://pav-ontology.googlecode.com/svn/trunk/pav.owl 
 * @author Auto-generated by schemagen on 14 Sep 2012 15:21 
 */
public class Rr {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/ns/r2rml#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** Names a column in the child table of a join
     */
    public static final Property child = m_model.createProperty( "http://www.w3.org/ns/r2rml#child" );
    
    /** Specifies the join condition for joining the child logical table with the parent logical table of the foreign key constraint.
     */
    public static final Property joinCondition = m_model.createProperty( "http://www.w3.org/ns/r2rml#joinCondition" );
    
    /** Schema-qualified name of a table or view.
     */
    public static final Property tableName = m_model.createProperty( "http://www.w3.org/ns/r2rml#tableName" );
    
    /** Denotes a base database table or view.
     */
    public static final Resource BaseTableOrView = m_model.createResource( "http://www.w3.org/ns/r2rml#BaseTableOrView" );
    
    /** Name of a column in the logical table. When generating RDF triples from a logical table row, value from the specified column is used as the subject, predicate, or object (based upon the specific domain)..
     */
    public static final Property column = m_model.createProperty( "http://www.w3.org/ns/r2rml#column");
    
}
